force-app/main/default/objects/AWS_File__c/AWS_File__c.object-meta.xml
<CustomObject>
    <label>AWS File</label>
    <nameField>
        <label>AWS File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AWS Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AWS_File__c/fields/File_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>File_Timestamp__c</fullName>
    <label>File Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AWS_File__c/fields/Related_Object_ID__c.field-meta.xml
<CustomField>
    <fullName>Related_Object_ID__c</fullName>
    <label>Related Object ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_File__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/S3Settings__c/S3Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Amazon S3 Settings</description>
    <label>S3Settings</label>
</CustomObject>

force-app/main/default/objects/S3Settings__c/fields/awsAccessKeyId__c.field-meta.xml
<CustomField>
    <fullName>awsAccessKeyId__c</fullName>
    <label>AWS Access Key Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3Settings__c/fields/bucketName__c.field-meta.xml
<CustomField>
    <fullName>bucketName__c</fullName>
    <label>Bucket Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3Settings__c/fields/bucketRegion__c.field-meta.xml
<CustomField>
    <fullName>bucketRegion__c</fullName>
    <label>Bucket Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3Settings__c/fields/secretAccessKey__c.field-meta.xml
<CustomField>
    <fullName>secretAccessKey__c</fullName>
    <label>Secret Acccess Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AWS_S3_TestClass.cls
//  Test class for the AWS S3 File Upload LWC.
//
//  Copyright (c) 2022, salesforce.com, inc.
//  All rights reserved.
//  SPDX-License-Identifier: BSD-3-Clause
//  For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
//
//  Contact: john.meyer@salesforce.com

@isTest(isParallel=true)
private class AWS_S3_TestClass  {

    private static final String FILE_NAME = 'Test File';
    private static final String LAST_NAME = 'Sautter';

    @testSetup
    private static void setup () {
        Contact testContact = new Contact (FirstName = 'John', LastName = LAST_NAME);
        insert testContact;
        insert new AWS_File__c (
            Name = FILE_NAME,
            Related_Object_ID__c = testContact.Id,
            Size__c = 10000,
            File_Timestamp__c = DateTime.now()
        );
        insert new S3Settings__c (
            awsAccessKeyId__c = 'Test123',
            bucketName__c = 'salesforce-test',
            bucketRegion__c = 'us-east-1',
            secretAccessKey__c = 'verysecretkey'
        );
    }
 
    @isTest
    private static void testFileList () {
        System.Test.startTest();
        Id recordId = [SELECT Id FROM Contact WHERE LastName = :LAST_NAME].Id;
        System.assertNotEquals(0, AWS_S3_Controller.queryAWSFiles(recordId).size());
        System.Test.stopTest();
    }

    @isTest
    private static void testCreateNewRecord () {
        System.Test.startTest();
        try {
            Id recordId = [SELECT Id FROM Contact WHERE LastName = :LAST_NAME].Id;
            AWS_File__c file = AWS_S3_Controller.createFileRecord(recordId, 'New File', 100, String.valueOf(DateTime.now().getTime()));
            System.assertNotEquals(null, file);
        } catch (Exception e) {
            System.assert(false);
        }
        System.Test.stopTest();
    }

    @isTest
    private static void testUpdateOldRecord () {
        System.Test.startTest();
        try {
            Id recordId = [SELECT Id FROM Contact WHERE LastName = :LAST_NAME].Id;
            AWS_File__c file = AWS_S3_Controller.createFileRecord(recordId, FILE_NAME, 200, String.valueOf(DateTime.now().getTime()));
            System.assertNotEquals(null, file);
        } catch (Exception e) {
            System.assert(false);
        }
        System.Test.stopTest();
    }

    @isTest
    private static void testSignedUrl () {

        System.Test.startTest();
		System.Test.setMock(HttpCalloutMock.class, new AWS_S3_TestHttpMock());
        Id recordId = [SELECT Id FROM Contact WHERE LastName = :LAST_NAME].Id;
        AWS_S3_Controller.deleteS3FileFromTrigger(recordId, FILE_NAME);
        System.Test.stopTest();
    }

}